export const lawsuitStates = [
  { name: 'Nhập mới' },
  { name: 'Nộp hồ sơ' },
  { name: 'Nhận thông báo TUAP' },
  { name: 'Tòa thụ lý hồ sơ' },
  { name: 'Nộp tự khai' },
  { name: 'Hòa giải' },
  { name: 'Xét xử' },
  { name: 'Xét xử sơ thẩm' },
  { name: 'Kháng cáo (NH)' },
  { name: 'Kháng cáo (KH)' },
  { name: 'Nộp đơn KC' },
  { name: 'Nhận thông báo TUAP KC' },
  { name: 'Tòa thụ lý hồ sơ KC' },
  { name: 'Phúc thẩm' },
  { name: 'Xét xử phúc thẩm' },
  { name: 'Hòa giải thành' },
  { name: 'Đình chỉ' },
  { name: 'Rút đơn' },
  { name: 'Trả đơn' },
]
